### ISSUE TITLE
Vectorize

### ISSUE THREAD

**Issue by jeanconn** [sot/Quaternion#3]
Should Quaternion be updated to use the vector forms in 

https://github.com/sot/mica/blob/master/mica/quaternion.py

?

**Comment by taldcroft** [comment]
Perhaps, but is there an immediate driver?

**Comment by jeanconn** [comment]
The immediate driver is that if you are updating Quaternion, the two
"branches" are diverging.

**Comment by taldcroft** [comment]
Can you make an actual branch and PR for the vectorized version?  I recall having some reservations about the implementation but I don't remember details.

**Comment by jeanconn** [comment]
The actual branch is still there.  I'll take an action to clean it up to
largely match mica.quaternion and make a PR.

**Comment by jeanconn** [comment]
Closed by #5
